version: '2'

services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    environment:
    - TZ=Europe/London
  celery-worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
    - '.:/usr/src/app'
    depends_on:
    - redis
    environment:
    - TZ=Europe/London
  celery-flower:
    build: .
    command: flower -A tasks worker --port=5555
    volumes:
    - '.:/usr/src/app'
    depends_on:
    - redis
    environment:
    - TZ=Europe/London
    ports:
    - '5555:5555'

volumes:
  redis:
  celery-worker:
  celery-flower: