version: '2'

services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    environment:
    - TZ=Europe/London

  celery-worker-generate-tumbnail:
    build: .
    command: celery worker -A worker --loglevel=info -Q priority.high
    volumes:
    - '.:/usr/src/app'
    depends_on:
    - redis
    environment:
    - TZ=Europe/London

  celery-worker-process-video:
    build: .
    command: celery worker -A worker --loglevel=info -Q celery
    volumes:
    - '.:/usr/src/app'
    depends_on:
    - redis
    environment:
    - TZ=Europe/London

  app:
    build: .
    command: python app.py
    volumes:
    - '.:/usr/src/app'
    depends_on:
    - redis
    environment:
    - TZ=Europe/London
    ports:
      - '5000:5000'

volumes:
  redis:
  celery-worker-process-video:
  celery-worker-generate-tumbnail:
  app: